name = "heobot"
license = "MIT"
#licenselink = "https://github.com/.../.../LICENSE.md"
description = ""
homepage = "http://import.re"
tags = ["tags", "categories"]
features = ["", ""]

[author]
  name = "Jaewe Heo"
  homepage = "http://import.re"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
